### ISSUE TITLE
scala

### ISSUE THREAD

**Issue by zijie2333** [clips/topbox#10]
error: error while loading CharSequence, class file '/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
error: error while loading AnnotatedElement, class file '/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar(java/lang/reflect/AnnotatedElement.class)' is broken
(bad constant pool tag 18 at byte 76)

is there anything that can fix it?
Thanks!

**Comment by cmry** [comment]
related to #9
