### ISSUE TITLE
Java problem, 'xxx is broken'

### ISSUE THREAD

**Issue by m-final** [clips/topbox#3]
While trying to run the sample code, encounter with below Java errors:

```
error: error while loading CharSequence, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
(bad constant pool tag 18 at byte 10)
error: error while loading AnnotatedElement, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre/lib/rt.jar(java/lang/reflect/AnnotatedElement.class)' is broken
```

Concretely, First it said my mac has not install JDK. then I picked one from Java official website, here's info:
```
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```
But still can't let it run. I've searched and looks like it comes from the version-incompatible about __sbt__, while I know few about it. so any help?

**Comment by cmry** [comment]
This is a Java-sided error (and therefore either your machine or Stanford's code). I'd suggest to try version 1.7 and see if that works.

**Comment by m-final** [comment]
@cmry Yes, it do worked after turned into Java 1.7, THANKS~
