### ISSUE TITLE
Parameter "epochs" doesn't make effect?

### ISSUE THREAD

**Issue by m-final** [clips/topbox#5]
When try to increase the iterations of LDA training,  I set the parameter `epochs` into a larger number like 30, but program still stopped at the point of 5 iterations.

Also I found the code in 198 line like `prep, std = 'maxIterations = ', ' 5'`
So seems program do not support changing of number of iterations currently, how should I do to make the algorithm's performance closing to the ideal one?

**Comment by cmry** [comment]
Confirmed, will look into it asap.

**Comment by cmry** [comment]
Fixed as of 6b3627c015be7bddeaee3bc6afb7cc90a661b9ae !
