### ISSUE TITLE
TypeError when calling stmt.results

### ISSUE THREAD

**Issue by roskoN** [clips/topbox#6]
Hey @cmry ,

Happy new year! I hope you had great holidays!

After doing some toy examples, I decided to go with you wrapper. :)

Unfortunately, I am facing an obstacle which I am not sure, whether it is related to what I am doing or is it something on the wrapper's side.

I am getting the following exception:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-13-30d9cf505532> in <module>()
      4 import scipy
      5 
----> 6 y_true, y_score = stmt.results(testLabels, array=False)
      7 print(y_true)
      8 print(y_score)

/home/rosko/GIT/twitter-ner/src/topbox/stmt.py in results(self, true_labels, array)
    358 
    359         y_true, y_score = self.get_scores(label_index, predicted_weights,
--> 360                                           true_labels)
    361 
    362         lbf.close()

/home/rosko/GIT/twitter-ner/src/topbox/stmt.py in get_scores(self, label_index, predicted_weights, true_labels)
    273             gold_standard = true_row.lower().split()
    274             rank, prob = zip(*self.m_incidence(predicted_row, label_index,
--> 275                                                gold_standard))
    276             if 1 in rank:
    277                 y_true.append(rank)

TypeError: type object argument after * must be an iterable, not NoneType
```
The code I use is:

```
stmt = topbox.STMT('named-entity-types', epochs=1000, mem=7000, keep=True)
stmt.train(trainLldaSpace, trainLldaLabels)

stmt.cleanup()

testEntities = ['x-men', 'world bank']
testLabel = ["geo-loc person movie band company sportsteam facility product tvshow other"]  * len(testEntities)

stmt.test(testEntities, testLabel)

y_true, y_score = stmt.results(testLabel, array=False)
print(y_true)
print(y_score)
```

Do you have any idea what might be the cause and how it could be fixed?

I have attached the trained model and the training data in JSON format - [model_train_data.zip](https://github.com/clips/topbox/files/684932/model_train_data.zip) .

Thank you for everything!

**Comment by cmry** [comment]
> Happy new year! I hope you had great holidays!

Why thank you :) same to you!

I would guess something's wrong with your code; `testLabels` doesn't seem to be declared (so you get a `NoneType` error). Could it be a mismatch between `testLabel` and `testLabels`?

**Comment by roskoN** [comment]
Oh my god. So embarrassing... 

Thank you and sorry to bother you with this!

**Comment by cmry** [comment]
Happens to the best. :)
