### ISSUE TITLE
some run questions

### ISSUE THREAD

**Issue by Kitaharakasusa** [clips/topbox#7]
I follow the readme step, but there are some question when I ran the test script you give,
I use Anaconda3 and download you code put it in the site-packages, the jar put in the box directory the error as follow ,could you give me some suggestion ?

C:\Anaconda3\Lib\site-packages\topbox\box\bit_of_testing_train.scala:14: error: invalid escape character
val source = CSVFile("C:\Anaconda3\Lib\site-packages	opbooit_of_testing_train.csv") ~> IDColumn(1);
                         ^
C:\Anaconda3\Lib\site-packages\topbox\box\bit_of_testing_train.scala:14: error: invalid escape character
val source = CSVFile("C:\Anaconda3\Lib\site-packages	opbooit_of_testing_train.csv") ~> IDColumn(1);
                                   ^
C:\Anaconda3\Lib\site-packages\topbox\box\bit_of_testing_train.scala:14: error: invalid escape character
val source = CSVFile("C:\Anaconda3\Lib\site-packages	opbooit_of_testing_train.csv") ~> IDColumn(1);
                                       ^
C:\Anaconda3\Lib\site-packages\topbox\box\bit_of_testing_train.scala:48: error: invalid escape character
val modelPath = file("C:\Anaconda3\Lib\site-packages	opbooit_of_testing_train");
                         ^
C:\Anaconda3\Lib\site-packages\topbox\box\bit_of_testing_train.scala:48: error: invalid escape character
val modelPath = file("C:\Anaconda3\Lib\site-packages	opbooit_of_testing_train");
                                   ^
C:\Anaconda3\Lib\site-packages\topbox\box\bit_of_testing_train.scala:48: error: invalid escape character
val modelPath = file("C:\Anaconda3\Lib\site-packages	opbooit_of_testing_train");
                                       ^
Traceback (most recent call last):
  File "D:/PycharmProjects/SentimentAnalysis/LDA/stf.py", line 9, in <module>
    stmt.train(space, labels)
  File "C:\Anaconda3\Lib\site-packages\topbox\stmt.py", line 438, in train
    self.run(space, labels, 'train')
  File "C:\Anaconda3\Lib\site-packages\topbox\stmt.py", line 420, in run
    self.boot(step)
  File "C:\Anaconda3\Lib\site-packages\topbox\stmt.py", line 123, in boot
    self.scala(mod, 1)
  File "C:\Anaconda3\Lib\site-packages\topbox\stmt.py", line 205, in scala
    self.regex(f, o_csv, n_csv) if not r else self.regex(f, n_csv, o_csv)
  File "C:\Anaconda3\Lib\site-packages\topbox\stmt.py", line 181, in regex
    stack = sub(needle, rock, rf.read())
  File "C:\Anaconda3\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Anaconda3\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Anaconda3\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Anaconda3\lib\sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Anaconda3\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "C:\Anaconda3\lib\sre_parse.py", line 502, in _parse
    code = _escape(source, this, state)
  File "C:\Anaconda3\lib\sre_parse.py", line 401, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
sre_constants.error: bad escape \L at position 12

**Comment by cmry** [comment]
Judging from this line:

```
 val source = CSVFile("C:\Anaconda3\Lib\site-packages opbooit_of_testing_train.csv") ~> IDColumn(1);
```

Something is causing `datafile.csv` to be incorrectly replaced. Can you provide a minimal example script that causes the error?

**Comment by Kitaharakasusa** [comment]
when I run the code
`import topbox

stmt = topbox.STMT('bit_of_testing', epochs=10, mem=15000)


space = ['text text more text', 'things to do with text']
labels = ['label1 label2', 'label1 label3']

stmt.train(space, labels)`
the error happend when I use the .train() and  it will generate two file in the box file
`bit _of_testing_train.csv
bit_of_testing_train.scala`

I don't have the scala environment,some others the generatefile code error is in these lines:
`val source = CSVFile("C:\Anaconda3\Lib\site-packages	opboxoxit_of_testing_train.csv") ~> IDColumn(1);
 val modelPath = file("C:\Anaconda3\Lib\site-packages	opboxoxit_of_testing_train");
`

**Comment by Kitaharakasusa** [comment]
when I run the code
```
import topbox

stmt = topbox.STMT('bit_of_testing', epochs=10, mem=15000)

space = ['text text more text', 'things to do with text']
labels = ['label1 label2', 'label1 label3']

stmt.train(space, labels)the error happend when I use the .train() 
```
and it will generate two file in the box file
```
bit _of_testing_train.csv
bit_of_testing_train.scala
```

I don't have the scala environment,some others the generatefile code error is in these lines:
```
val source = CSVFile("C:\Anaconda3\Lib\site-packages	opboxoxit_of_testing_train.csv") ~> IDColumn(1);
val modelPath = file("C:\Anaconda3\Lib\site-packages	opboxoxit_of_testing_train");
```
when i paste the scala code to the webpage there are some messy code

**Comment by cmry** [comment]
Ah, I see, this is some Windows compatibility issue. Seems like it's parsing the directory string (i.e. the `\t` part in `\topbox`  becomes a tab). I'll look into fixing this.

**Comment by Kitaharakasusa** [comment]
may I ask some other questions? I want to use your code to my study project. but I just get started to learn about LDA and LLDA. I'm  doubt about the model you implement if the model can be saved, what should I do when I want to used the trained model next time? I'll appreciate it very much if you could lend me a hand.

**Comment by cmry** [comment]
I added a normalization for the path, hopefully that fixes it. You can read up more on the workings of the Stanford Topic Modeling Toolbox [here](https://nlp.stanford.edu/software/tmt/tmt-0.4/), including how to apply a trained model to new data (under **Topic model inference on a new corpus**). Hope that helps!
